package mod.krevik.kathairis.init;

import mod.krevik.kathairis.block.BlockKathairianPortal;
import net.minecraft.block.Block;
import net.minecraftforge.registries.ObjectHolder;

import static mod.krevik.kathairis.util.ModReference.MOD_ID;

/**
 * @author Cadiboo
 */
@ObjectHolder(MOD_ID)
public final class ModBlocks {

	public static final Block KATHARIAN_STONE = null;
	public static final BlockKathairianPortal KATHARIAN_PORTAL = null;
	public static final Block KATHARIAN_DIRT = null;
	public static final Block KATHARIAN_GRASS = null;
	public static final Block TITANIUM_BLOCK = null;
	public static final Block MYSTIC_LOG = null;
	public static final Block MYSTIC_LEAVES = null;
	public static final Block SHINY_LOG = null;
	public static final Block SHINY_LEAVES = null;
	public static final Block SOUL_LOG = null;
	public static final Block SOUL_LEAVES = null;
	public static final Block REVENUM_ORE = null;
	public static final Block TITANIUM_ORE = null;
	public static final Block KATHARIAN_SAND = null;
	public static final Block SOFT_SAND = null;
	public static final Block BLUE_CLOUD = null;
	public static final Block YELLOW_CLOUD = null;
	public static final Block WEATHERED_ROCK = null;
	public static final Block MYSTIC_PLANKS = null;
	public static final Block SHINY_PLANKS = null;
	public static final Block SOUL_PLANKS = null;
	public static final Block KATHARIAN_COBBLESTONE = null;
	public static final Block KATHARIAN_STONE_TILES = null;
	public static final Block SHINY_ROCK = null;
	public static final Block KATHARIAN_STONE_BRICKS = null;
	public static final Block MUD_BLOCK = null;
	public static final Block MUD_BRICKS = null;
	public static final Block MAGNETHIUM = null;
	public static final Block IRON_GOLD_BLOCK = null;
	public static final Block HARDENED_WEATHERED_ROCK = null;
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS = null;
	public static final Block HARDENED_WEATHERED_ROCK_TILES = null;
	public static final Block BLUE_CLOUD_REFINED = null;
	public static final Block YELLOW_CLOUD_REFINED = null;
	public static final Block BLUE_CLOUD_CONDENSED = null;
	public static final Block YELLOW_CLOUD_CONDENSED = null;
	public static final Block MYSTIC_LOG_STRIPPED = null;
	public static final Block SHINY_LOG_STRIPPED = null;
	public static final Block SOUL_LOG_STRIPPED = null;
	public static final Block MYSTIC_WOOD_FENCE = null;
	public static final Block MYSTIC_WOOD_FENCE_GATE = null;
	public static final Block SHINY_WOOD_FENCE = null;
	public static final Block SHINY_WOOD_FENCE_GATE = null;
	public static final Block SOUL_WOOD_FENCE = null;
	public static final Block SOUL_WOOD_FENCE_GATE = null;
	public static final Block KATHARIAN_STONE_WALL = null;
	public static final Block KATHARIAN_COBBLESTONE_WALL = null;
	public static final Block WEATHERED_ROCK_WALL = null;
	public static final Block HARDENED_WEATHERED_ROCK_WALL = null;
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_WALL = null;
	public static final Block MUD_BRICKS_WALL = null;
	public static final Block KATHARIAN_STONE_BRICKS_WALL = null;
	public static final Block MYSTIC_WOOD_STAIRS = null;
	public static final Block SHINY_WOOD_STAIRS = null;
	public static final Block SOUL_WOOD_STAIRS = null;
	public static final Block KATHARIAN_STONE_STAIRS = null;
	public static final Block KATHARIAN_COBBLESTONE_STAIRS = null;
	public static final Block WEATHERED_ROCK_STAIRS = null;
	public static final Block HARDENED_WEATHERED_ROCK_STAIRS = null;
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_STAIRS = null;
	public static final Block MUD_BRICKS_STAIRS = null;
	public static final Block KATHARIAN_STONE_BRICKS_STAIRS = null;
	public static final Block KATHARIAN_STONE_SLAB = null;
	public static final Block KATHARIAN_COBBLESTONE_SLAB = null;
	public static final Block KATHARIAN_STONE_BRICKS_SLAB = null;
	public static final Block MUD_BRICKS_SLAB = null;
	public static final Block MYSTIC_WOOD_SLAB = null;
	public static final Block SHINY_WOOD_SLAB = null;
	public static final Block SOUL_WOOD_SLAB = null;
	public static final Block WEATHERED_ROCK_SLAB = null;
	public static final Block HARDENED_WEATHERED_ROCK_SLAB = null;
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_SLAB = null;
	public static final Block BLUE_CRYSTAL = null;
	public static final Block VIOLET_CRYSTAL = null;
	public static final Block YELLOW_CRYSTAL = null;
	public static final Block BISON_STARS = null;
	public static final Block EYE_PLANT = null;
	public static final Block KATHARIAN_MINI_GRASS = null;
	public static final Block KATHARIAN_TALL_GRASS = null;
	public static final Block KATHARIAN_NIGHT_FLOWER = null;
	public static final Block KATHARIAN_MULTI_GRASS = null;
	public static final Block BLUE_CLOUD_BRICKS = null;
	public static final Block YELLOW_CLOUD_BLOCK = null;
	public static final Block FRUP_PLANT = null;
	public static final Block MYSTIC_WOOD_DOORS = null;
	public static final Block SHINY_WOOD_DOORS = null;
	public static final Block SOUL_WOOD_DOORS = null;
	public static final Block MYSTIC_WOOD_TRAPDOOR = null;
	public static final Block SHINY_WOOD_TRAPDOOR = null;
	public static final Block SOUL_WOOD_TRAPDOOR = null;
	public static final Block KATHARIAN_FUNGI = null;
	public static final Block GOOSEBERRY_BUSH = null;
	public static final Block KATHARIAN_SUCCULENT = null;
	public static final Block STEPPED_SUCCULENT = null;
	public static final Block VILYRIA = null;
	public static final Block GLOWVINES = null;
	public static final Block JADE_VINES = null;
	public static final Block KATHARIAN_DEAD_GRASS = null;
	public static final Block MYSTIC_GEM_BLOCK = null;
	public static final Block MAGIC_BEANS = null;
	public static final Block BAURBLE = null;
	public static final Block BUTTERFLY_FLOWER = null;
	public static final Block SOLIS_CRYSTALS = null;
	public static final Block BLUE_CLOUD_FLOWER = null;
	public static final Block YELLOW_CLOUD_FLOWER = null;
	public static final Block SNOWDROP_CYPREPEDIUM = null;
	public static final Block FLUO_FUNGI = null;
	public static final Block LAYERED_SAND = null;
	public static final Block KATHARIAN_SANDSTONE = null;
	public static final Block FOREST_CANDLE = null;
	public static final Block ROCKTUS = null;
	public static final Block ELDERWILLOW_LOG = null;
	public static final Block ELDERWILLOW_LEAVES = null;

}
