# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[24,)" #mandatory (24 is current forge version)

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://github.com/Krevik/Kathairis/update.json" #optional

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Krevik/Kathairis/issues" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/beta-kathairis" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="kathairis.png" #optional

# A text field displayed in the mod UI
credits="FreeSound.org for their great audio samples;
MCVinnyQ and HKDragonBoy for textures and Models;
it3b for their amazing musical work;
RavenOfTheWastes for his writing and community management;
ShadowWalkerEraZ and our Beta testing team for helping ensure the mod is functional and (mostly) bug-free;
Cadiboo for being the best minecraft coder on this and that world
Special thanks to past members of the development team: Feranogame, Oktet, and Mystical Spire" #optional

# A text field displayed in the mod UI
authors="Krevik" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="kathairis" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory

 # A display name for the mod
displayName="Kathairis" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
description='''
Kathairis is a whole new dimension with a rich back-story, many new mobs, and so much more!
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.kathairis]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[24,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

# Here's another dependency
[[dependencies.kathairis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"
