package io.github.krevik.kathairis.init;

import io.github.krevik.kathairis.block.BlockKathairisPortal;
import io.github.krevik.kathairis.util.ModUtil;
import net.minecraft.block.Block;
import net.minecraftforge.registries.ObjectHolder;

import static io.github.krevik.kathairis.util.ModReference.MOD_ID;
import static io.github.krevik.kathairis.util.ModUtil._null;

/**
 * @author Cadiboo
 */
@ObjectHolder(MOD_ID)
public final class ModBlocks {

	public static final Block KATHAIRIS_STONE = _null();
	public static final BlockKathairisPortal KATHAIRIS_PORTAL = _null();
	public static final Block KATHAIRIS_DIRT = _null();
	public static final Block KATHAIRIS_GRASS = _null();
	public static final Block TITANIUM_BLOCK = _null();
	public static final Block MYSTIC_LOG = _null();
	public static final Block MYSTIC_LEAVES = _null();
	public static final Block SHINY_LOG = _null();
	public static final Block SHINY_LEAVES = _null();
	public static final Block SOUL_LOG = _null();
	public static final Block SOUL_LEAVES = _null();
	public static final Block REVENUM_ORE = _null();
	public static final Block TITANIUM_ORE = _null();
	public static final Block KATHAIRIS_SAND = _null();
	public static final Block SOFT_SAND = _null();
	public static final Block BLUE_CLOUD = _null();
	public static final Block YELLOW_CLOUD = _null();
	public static final Block WEATHERED_ROCK = _null();
	public static final Block MYSTIC_PLANKS = _null();
	public static final Block SHINY_PLANKS = _null();
	public static final Block SOUL_PLANKS = _null();
	public static final Block KATHAIRIS_COBBLESTONE = _null();
	public static final Block KATHAIRIS_STONE_TILES = _null();
	public static final Block SHINY_ROCK = _null();
	public static final Block KATHAIRIS_STONE_BRICKS = _null();
	public static final Block MUD_BLOCK = _null();
	public static final Block MUD_BRICKS = _null();
	public static final Block MAGNETHIUM = _null();
	public static final Block IRON_GOLD_BLOCK = _null();
	public static final Block HARDENED_WEATHERED_ROCK = _null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS = _null();
	public static final Block HARDENED_WEATHERED_ROCK_TILES = _null();
	public static final Block BLUE_CLOUD_REFINED = _null();
	public static final Block YELLOW_CLOUD_REFINED = _null();
	public static final Block BLUE_CLOUD_CONDENSED = _null();
	public static final Block YELLOW_CLOUD_CONDENSED = _null();
	public static final Block MYSTIC_LOG_STRIPPED = _null();
	public static final Block SHINY_LOG_STRIPPED = _null();
	public static final Block SOUL_LOG_STRIPPED = _null();
	public static final Block MYSTIC_WOOD_FENCE = _null();
	public static final Block MYSTIC_WOOD_FENCE_GATE = _null();
	public static final Block SHINY_WOOD_FENCE = _null();
	public static final Block SHINY_WOOD_FENCE_GATE = _null();
	public static final Block SOUL_WOOD_FENCE = _null();
	public static final Block SOUL_WOOD_FENCE_GATE = _null();
	public static final Block KATHAIRIS_STONE_WALL = _null();
	public static final Block KATHAIRIS_COBBLESTONE_WALL = _null();
	public static final Block WEATHERED_ROCK_WALL = _null();
	public static final Block HARDENED_WEATHERED_ROCK_WALL = _null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_WALL = _null();
	public static final Block MUD_BRICKS_WALL = _null();
	public static final Block KATHAIRIS_STONE_BRICKS_WALL = _null();
	public static final Block MYSTIC_WOOD_STAIRS = _null();
	public static final Block SHINY_WOOD_STAIRS = _null();
	public static final Block SOUL_WOOD_STAIRS = _null();
	public static final Block KATHAIRIS_STONE_STAIRS = _null();
	public static final Block KATHAIRIS_COBBLESTONE_STAIRS = _null();
	public static final Block WEATHERED_ROCK_STAIRS = _null();
	public static final Block HARDENED_WEATHERED_ROCK_STAIRS = _null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_STAIRS = _null();
	public static final Block MUD_BRICKS_STAIRS = _null();
	public static final Block KATHAIRIS_STONE_BRICKS_STAIRS = _null();
	public static final Block KATHAIRIS_STONE_SLAB = _null();
	public static final Block KATHAIRIS_COBBLESTONE_SLAB = _null();
	public static final Block KATHAIRIS_STONE_BRICKS_SLAB = _null();
	public static final Block MUD_BRICKS_SLAB = _null();
	public static final Block MYSTIC_WOOD_SLAB = _null();
	public static final Block SHINY_WOOD_SLAB = _null();
	public static final Block SOUL_WOOD_SLAB = _null();
	public static final Block WEATHERED_ROCK_SLAB = _null();
	public static final Block HARDENED_WEATHERED_ROCK_SLAB = _null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_SLAB = _null();
	public static final Block BLUE_CRYSTAL = _null();
	public static final Block VIOLET_CRYSTAL = _null();
	public static final Block YELLOW_CRYSTAL = _null();
	public static final Block BISON_STARS = _null();
	public static final Block EYE_PLANT = _null();
	public static final Block KATHAIRIS_MINI_GRASS = _null();
	public static final Block KATHAIRIS_TALL_GRASS = _null();
	public static final Block KATHAIRIS_NIGHT_FLOWER = _null();
	public static final Block KATHAIRIS_MULTI_GRASS = _null();
	public static final Block BLUE_CLOUD_BRICKS = _null();
	public static final Block YELLOW_CLOUD_BLOCK = _null();
	public static final Block FRUP_PLANT = _null();
	public static final Block MYSTIC_WOOD_DOORS = _null();
	public static final Block SHINY_WOOD_DOORS = _null();
	public static final Block SOUL_WOOD_DOORS = _null();
	public static final Block MYSTIC_WOOD_TRAPDOOR = _null();
	public static final Block SHINY_WOOD_TRAPDOOR = _null();
	public static final Block SOUL_WOOD_TRAPDOOR = _null();
	public static final Block KATHAIRIS_FUNGI = _null();
	public static final Block GOOSEBERRY_BUSH = _null();
	public static final Block KATHAIRIS_SUCCULENT = _null();
	public static final Block STEPPED_SUCCULENT = _null();
	public static final Block VILYRIA = _null();
	public static final Block GLOWVINES = _null();
	public static final Block JADE_VINES = _null();
	public static final Block KATHAIRIS_DEAD_GRASS = _null();
	public static final Block MYSTIC_GEM_BLOCK = _null();
	public static final Block MAGIC_BEANS = _null();
	public static final Block BAURBLE = _null();
	public static final Block BUTTERFLY_FLOWER = _null();
	public static final Block SOLIS_CRYSTALS = _null();
	public static final Block BLUE_CLOUD_FLOWER = _null();
	public static final Block YELLOW_CLOUD_FLOWER = _null();
	public static final Block SNOWDROP_CYPREPEDIUM = _null();
	public static final Block FLUO_FUNGI = _null();
	public static final Block LAYERED_SAND = _null();
	public static final Block KATHAIRIS_SANDSTONE = _null();
	public static final Block FOREST_CANDLE = _null();
	public static final Block ROCKTUS = _null();
	public static final Block ELDERWILLOW_LOG = _null();
	public static final Block ELDERWILLOW_LEAVES = _null();

}
