package io.github.krevik.kathairis.init;

import io.github.krevik.kathairis.block.BlockKathairisPortal;
import io.github.krevik.kathairis.util.ModUtil;
import net.minecraft.block.Block;
import net.minecraftforge.registries.ObjectHolder;

import static io.github.krevik.kathairis.util.ModReference.MOD_ID;

/**
 * @author Cadiboo
 */
@ObjectHolder(MOD_ID)
public final class ModBlocks {

	public static final Block KATHARIAN_STONE = ModUtil._null();
	public static final BlockKathairisPortal KATHAIRIS_PORTAL = ModUtil._null();
	public static final Block KATHARIAN_DIRT = ModUtil._null();
	public static final Block KATHARIAN_GRASS = ModUtil._null();
	public static final Block TITANIUM_BLOCK = ModUtil._null();
	public static final Block MYSTIC_LOG = ModUtil._null();
	public static final Block MYSTIC_LEAVES = ModUtil._null();
	public static final Block SHINY_LOG = ModUtil._null();
	public static final Block SHINY_LEAVES = ModUtil._null();
	public static final Block SOUL_LOG = ModUtil._null();
	public static final Block SOUL_LEAVES = ModUtil._null();
	public static final Block REVENUM_ORE = ModUtil._null();
	public static final Block TITANIUM_ORE = ModUtil._null();
	public static final Block KATHARIAN_SAND = ModUtil._null();
	public static final Block SOFT_SAND = ModUtil._null();
	public static final Block BLUE_CLOUD = ModUtil._null();
	public static final Block YELLOW_CLOUD = ModUtil._null();
	public static final Block WEATHERED_ROCK = ModUtil._null();
	public static final Block MYSTIC_PLANKS = ModUtil._null();
	public static final Block SHINY_PLANKS = ModUtil._null();
	public static final Block SOUL_PLANKS = ModUtil._null();
	public static final Block KATHARIAN_COBBLESTONE = ModUtil._null();
	public static final Block KATHARIAN_STONE_TILES = ModUtil._null();
	public static final Block SHINY_ROCK = ModUtil._null();
	public static final Block KATHARIAN_STONE_BRICKS = ModUtil._null();
	public static final Block MUD_BLOCK = ModUtil._null();
	public static final Block MUD_BRICKS = ModUtil._null();
	public static final Block MAGNETHIUM = ModUtil._null();
	public static final Block IRON_GOLD_BLOCK = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_TILES = ModUtil._null();
	public static final Block BLUE_CLOUD_REFINED = ModUtil._null();
	public static final Block YELLOW_CLOUD_REFINED = ModUtil._null();
	public static final Block BLUE_CLOUD_CONDENSED = ModUtil._null();
	public static final Block YELLOW_CLOUD_CONDENSED = ModUtil._null();
	public static final Block MYSTIC_LOG_STRIPPED = ModUtil._null();
	public static final Block SHINY_LOG_STRIPPED = ModUtil._null();
	public static final Block SOUL_LOG_STRIPPED = ModUtil._null();
	public static final Block MYSTIC_WOOD_FENCE = ModUtil._null();
	public static final Block MYSTIC_WOOD_FENCE_GATE = ModUtil._null();
	public static final Block SHINY_WOOD_FENCE = ModUtil._null();
	public static final Block SHINY_WOOD_FENCE_GATE = ModUtil._null();
	public static final Block SOUL_WOOD_FENCE = ModUtil._null();
	public static final Block SOUL_WOOD_FENCE_GATE = ModUtil._null();
	public static final Block KATHARIAN_STONE_WALL = ModUtil._null();
	public static final Block KATHARIAN_COBBLESTONE_WALL = ModUtil._null();
	public static final Block WEATHERED_ROCK_WALL = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_WALL = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_WALL = ModUtil._null();
	public static final Block MUD_BRICKS_WALL = ModUtil._null();
	public static final Block KATHARIAN_STONE_BRICKS_WALL = ModUtil._null();
	public static final Block MYSTIC_WOOD_STAIRS = ModUtil._null();
	public static final Block SHINY_WOOD_STAIRS = ModUtil._null();
	public static final Block SOUL_WOOD_STAIRS = ModUtil._null();
	public static final Block KATHARIAN_STONE_STAIRS = ModUtil._null();
	public static final Block KATHARIAN_COBBLESTONE_STAIRS = ModUtil._null();
	public static final Block WEATHERED_ROCK_STAIRS = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_STAIRS = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_STAIRS = ModUtil._null();
	public static final Block MUD_BRICKS_STAIRS = ModUtil._null();
	public static final Block KATHARIAN_STONE_BRICKS_STAIRS = ModUtil._null();
	public static final Block KATHARIAN_STONE_SLAB = ModUtil._null();
	public static final Block KATHARIAN_COBBLESTONE_SLAB = ModUtil._null();
	public static final Block KATHARIAN_STONE_BRICKS_SLAB = ModUtil._null();
	public static final Block MUD_BRICKS_SLAB = ModUtil._null();
	public static final Block MYSTIC_WOOD_SLAB = ModUtil._null();
	public static final Block SHINY_WOOD_SLAB = ModUtil._null();
	public static final Block SOUL_WOOD_SLAB = ModUtil._null();
	public static final Block WEATHERED_ROCK_SLAB = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_SLAB = ModUtil._null();
	public static final Block HARDENED_WEATHERED_ROCK_BRICKS_SLAB = ModUtil._null();
	public static final Block BLUE_CRYSTAL = ModUtil._null();
	public static final Block VIOLET_CRYSTAL = ModUtil._null();
	public static final Block YELLOW_CRYSTAL = ModUtil._null();
	public static final Block BISON_STARS = ModUtil._null();
	public static final Block EYE_PLANT = ModUtil._null();
	public static final Block KATHARIAN_MINI_GRASS = ModUtil._null();
	public static final Block KATHARIAN_TALL_GRASS = ModUtil._null();
	public static final Block KATHARIAN_NIGHT_FLOWER = ModUtil._null();
	public static final Block KATHARIAN_MULTI_GRASS = ModUtil._null();
	public static final Block BLUE_CLOUD_BRICKS = ModUtil._null();
	public static final Block YELLOW_CLOUD_BLOCK = ModUtil._null();
	public static final Block FRUP_PLANT = ModUtil._null();
	public static final Block MYSTIC_WOOD_DOORS = ModUtil._null();
	public static final Block SHINY_WOOD_DOORS = ModUtil._null();
	public static final Block SOUL_WOOD_DOORS = ModUtil._null();
	public static final Block MYSTIC_WOOD_TRAPDOOR = ModUtil._null();
	public static final Block SHINY_WOOD_TRAPDOOR = ModUtil._null();
	public static final Block SOUL_WOOD_TRAPDOOR = ModUtil._null();
	public static final Block KATHARIAN_FUNGI = ModUtil._null();
	public static final Block GOOSEBERRY_BUSH = ModUtil._null();
	public static final Block KATHARIAN_SUCCULENT = ModUtil._null();
	public static final Block STEPPED_SUCCULENT = ModUtil._null();
	public static final Block VILYRIA = ModUtil._null();
	public static final Block GLOWVINES = ModUtil._null();
	public static final Block JADE_VINES = ModUtil._null();
	public static final Block KATHARIAN_DEAD_GRASS = ModUtil._null();
	public static final Block MYSTIC_GEM_BLOCK = ModUtil._null();
	public static final Block MAGIC_BEANS = ModUtil._null();
	public static final Block BAURBLE = ModUtil._null();
	public static final Block BUTTERFLY_FLOWER = ModUtil._null();
	public static final Block SOLIS_CRYSTALS = ModUtil._null();
	public static final Block BLUE_CLOUD_FLOWER = ModUtil._null();
	public static final Block YELLOW_CLOUD_FLOWER = ModUtil._null();
	public static final Block SNOWDROP_CYPREPEDIUM = ModUtil._null();
	public static final Block FLUO_FUNGI = ModUtil._null();
	public static final Block LAYERED_SAND = ModUtil._null();
	public static final Block KATHARIAN_SANDSTONE = ModUtil._null();
	public static final Block FOREST_CANDLE = ModUtil._null();
	public static final Block ROCKTUS = ModUtil._null();
	public static final Block ELDERWILLOW_LOG = ModUtil._null();
	public static final Block ELDERWILLOW_LEAVES = ModUtil._null();

}
